version: '3'

# TODO: unfinished
services:
  redis:
    image: redis:6
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: remind_me
      POSTGRES_USER: remind_me
      POSTGRES_PASSWORD: remind_me
  api:
    build: ./backend
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://remind_me:remind_me@db:5432/remind_me
      JWT_SECRET: keyboard cat
      PORT: '8000'
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    restart: always
